name: Workflow for Codecov maize
on:
  push:
    branches:
      - '*'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          source $HOME/.poetry/env
      - name: Install project dependencies
        run: poetry install
      - name: Run tests and collect coverage
        run: poetry run pytest --cov maize
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
